//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BogCafeteria.Entity_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public int Company { get; set; }
        public int Type { get; set; }
        public string Comment1 { get; set; }
    
        public virtual Company Company1 { get; set; }
        public virtual CommentType CommentType { get; set; }
    }
}
